name: Deploy Automático

on:
  push:
    branches:
      - main  # ou master, dependendo do nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: BrunoMacedo87
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build e Push do Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: brunomacedo87/testenota-backend:latest

      - name: Build e Push do Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: brunomacedo87/testenota-frontend:latest

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adicionar servidor ao known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 23.88.124.38 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh deploy@23.88.124.38 'cd /var/www/testenota && docker compose pull && docker compose up -d --force-recreate'
